spring:
  application:
    name: dango-ai-code-user
  profiles:
    active: local
  session:
    store-type: redis
    # session 10 年过期
    timeout: 315360000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 10 年过期
    session:
      cookie:
        max-age: 315360000
