apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    uid: mysql-business
    access: proxy
    url: ${MYSQL_GRAFANA_HOST}:${MYSQL_GRAFANA_PORT}
    database: ${MYSQL_GRAFANA_DATABASE}
    user: ${MYSQL_GRAFANA_USER}
    secureJsonData:
      password: ${MYSQL_GRAFANA_PASSWORD}
    editable: false
    jsonData:
      maxOpenConns: 2
      maxIdleConns: 2
      connMaxLifetime: 14400
      timezone: Asia/Shanghai
