apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    uid: redis-direct
    access: proxy
    url: redis://${REDIS_HOST}:${REDIS_PORT}
    secureJsonData:
      password: ${REDIS_PASSWORD}
    editable: false
    jsonData:
      client: standalone
