apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: ${ALERT_EMAIL_TO}
        disableResolveMessage: false
