apiVersion: 1

policies:
  - orgId: 1
    receiver: default-email
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: default-email
        matchers:
          - severity = critical
        repeat_interval: 1h
